on: 
  push:
    branches:
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://mystertech.com:221
        ftp-username: 3441847_mystertech
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        git-ftp-args: --insecure
